(define (halve n) (/ n 2))
(define (double n) (+ n n))
(define (fast-mult a b)
    (cond ((= b 0) 0)
          ((= (remainder b 2) 0) (fast-mult (double a) (halve b)))
          (else (+ a (fast-mult a (- b 1))))))
